# Generated by Django 3.2.4 on 2021-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.CharField(max_length=250)),
                ('Sub_County', models.CharField(max_length=250)),
                ('Health_Facility_Name', models.CharField(max_length=250)),
                ('Latitudes', models.DecimalField(decimal_places=12, max_digits=100, max_length=100)),
                ('Longitudes', models.DecimalField(decimal_places=12, max_digits=100, max_length=100)),
            ],
        ),
    ]
