# Generated by Django 3.2.4 on 2021-10-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covaxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='County',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='Health_Facility_Name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='Latitudes',
            field=models.DecimalField(decimal_places=12, max_digits=100, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='Longitudes',
            field=models.DecimalField(decimal_places=12, max_digits=100, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='Sub_County',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
